### ISSUE TITLE
orphan blocks for bytecoin

### ISSUE THREAD

**Issue by cycleworm** [sevendoorknobs/BCN-Cryptonote-Pool#1]
Hi guys. does anybody know if this fork can handle orphan blocks for mining bytecoin correctly?

With one fork i had the problem that all blocks were marked as orphans and therefore not payment to the miners did happen.

And with another fork i had the problem that the orphans were not recognized and all miners were payed even if there was no block reward for the pool (because of orphaned block)

Thanks a lot

**Comment by sevendoorknobs** [comment]
The blocks were not mined as orphans, they just displayed that way on the front end due to a difference between monero and bytecoin.
