### ISSUE TITLE
Transaction fee are not working on config.json

### ISSUE THREAD

**Issue by rigoy22k** [sevendoorknobs/BCN-Cryptonote-Pool#3]
this is my config:
 
"payments": {
        "enabled": true,
        "interval": 480,
        "maxAddresses": 50,
        "mixin": 0,
        "transferFee": 10000,
        "minPayment": 100000000,
        "maxTransactionAmount": 0,
        "denomination": 10000000
    },

doesn't matter any change on "transferFee": always get 1 on fee:

2018-Feb-04 03:49:57.791748 INFO    Wallet balance updated, address LMWGEVoUmBfCB2nii8j6PBTc7a6pEgYHyGDFTLueQG9dZyphSvpmohaRsyZMkoKUCRfC4fDUGqtpx4TP1AigkRTFPGVc6R2, actual 320.72037028, pending 0.00000000
2018-Feb-04 03:49:57.792436 INFO    Container balance updated, actual 320.72037028, pending 0.00000000
2018-Feb-04 03:50:33.948615 INFO    transfer, from {}, to {<23.50000000, LHAzGUZbZ6kchwrF1FRZkZPLxyHGjkjAYT8GczvXCnx951MvEsfP5PHdEv2u6Lti1HQkEMDGhgvmyKrKf4tQwAbw8dQV98C>}, change address '', **fee 1.00000000,** mixin 2, unlockTimestamp 0

**Comment by rigoy22k** [comment]
fee hardcode on payments.js ??

87 | amount: 0,
-- | --
88 | rpc: {
89 | transfers: [],
**90 | fee: 100000000,**
… |  
128 | txHash,
129 | transferCmd.amount,
130 | transferCmd.rpc.fee,

**Comment by sevendoorknobs** [comment]
Yes this was because of a bug in the communication between the files, will be fixed in the future.
